/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ADC0.h
**     Project     : CB_Test
**     Processor   : MK22FN512VLH12
**     Component   : fsl_adc16
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-03-03, 14:46, # CodeGen: 32
**     Contents    :
**         ADC16_DRV_GetAutoCalibrationParam     - adc16_status_t ADC16_DRV_GetAutoCalibrationParam(uint32_t...
**         ADC16_DRV_SetCalibrationParam         - adc16_status_t ADC16_DRV_SetCalibrationParam(uint32_t...
**         ADC16_DRV_StructInitUserConfigDefault - adc16_status_t ADC16_DRV_StructInitUserConfigDefault(adc16_user_config_t *...
**         ADC16_DRV_Init                        - adc16_status_t ADC16_DRV_Init(uint32_t instance,adc16_user_config_t *...
**         ADC16_DRV_Deinit                      - void ADC16_DRV_Deinit(uint32_t instance);
**         ADC16_DRV_EnableLongSample            - void ADC16_DRV_EnableLongSample(uint32_t...
**         ADC16_DRV_DisableLongSample           - void ADC16_DRV_DisableLongSample(uint32_t instance);
**         ADC16_DRV_EnableHwCmp                 - adc16_status_t ADC16_DRV_EnableHwCmp(uint32_t instance,adc16_hw_cmp_config_t...
**         ADC16_DRV_DisableHwCmp                - void ADC16_DRV_DisableHwCmp(uint32_t instance);
**         ADC16_DRV_EnableHwAverage             - void ADC16_DRV_EnableHwAverage(uint32_t...
**         ADC16_DRV_DisableHwAverage            - void ADC16_DRV_DisableHwAverage(uint32_t instance);
**         ADC16_DRV_ConfigConvChn               - adc16_status_t ADC16_DRV_ConfigConvChn(uint32_t instance,uint32_t...
**         ADC16_DRV_WaitConvDone                - void ADC16_DRV_WaitConvDone(uint32_t instance,uint32_t chnGroup);
**         ADC16_DRV_PauseConv                   - void ADC16_DRV_PauseConv(uint32_t instance,uint32_t chnGroup);
**         ADC16_DRV_GetConvValueRAW             - uint16_t ADC16_DRV_GetConvValueRAW(uint32_t instance,uint32_t chnGroup);
**         ADC16_DRV_ConvRAWData                 - int32_t ADC16_DRV_ConvRAWData(uint16_t convValue,bool...
**         ADC16_DRV_GetFlag                     - bool ADC16_DRV_GetFlag(uint32_t instance,adc16_flag_t flag);
**         ADC16_DRV_GetChnFlag                  - bool ADC16_DRV_GetChnFlag(uint32_t instance,uint32_t chnGroup,adc16_flag_t...
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file ADC0.h
** @version 01.00
*/         
/*!
**  @addtogroup ADC0_module ADC0 module documentation
**  @{
*/         
#ifndef __ADC0_H
#define __ADC0_H
/* MODULE ADC0. */
/* Include inherited beans */
#include "Cpu.h"


/*! @brief Device instance number */
#define FSL_ADC0 0

/*! @brief User configuration structure 0 */
extern adc16_user_config_t ADC0_InitConfig0;

/*! @brief User channel configuration structure 0 */
extern adc16_chn_config_t ADC0_ChnConfig0;
/*! @brief User channel configuration structure 1 */
extern adc16_chn_config_t ADC0_ChnConfig1;
/*! @brief User channel configuration structure 2 */
extern adc16_chn_config_t ADC0_ChnConfig2;
  

 
#endif
/* ifndef __ADC0_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.11]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
