/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ADC0.c
**     Project     : CB_Test
**     Processor   : MK22FN512VLH12
**     Component   : fsl_adc16
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-03-04, 17:52, # CodeGen: 36
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file ADC0.c
** @version 01.00
*/         
/*!
**  @addtogroup ADC0_module ADC0 module documentation
**  @{
*/         

/* MODULE ADC0. */

#include "Events.h"
#include "ADC0.h"

adc16_user_config_t ADC0_InitConfig0 = {
  .intEnable            = false,
  .lowPowerEnable       = false,
  .resolutionMode       = kAdcResolutionBitOf16,
  .clkSrcMode           = kAdcClkSrcOfAsynClk,
  .clkDividerMode       = kAdcClkDividerInputOf1,
  .asyncClkEnable       = true,
  .highSpeedEnable      = true,
  .hwTriggerEnable      = false,
  .dmaEnable            = false,
  .refVoltSrcMode       = kAdcRefVoltSrcOfVref,
  .continuousConvEnable = false
    
};
        
adc16_chn_config_t ADC0_ChnConfig0 = {
  .chnNum     = 0U,
  .diffEnable = false,
  .intEnable  = false,
  .chnMux     = kAdcChnMuxOfA
};
      
adc16_chn_config_t ADC0_ChnConfig1 = {
  .chnNum     = 19U,
  .diffEnable = false,
  .intEnable  = false,
  .chnMux     = kAdcChnMuxOfA
};
      
adc16_chn_config_t ADC0_ChnConfig2 = {
  .chnNum     = 3U,
  .diffEnable = false,
  .intEnable  = false,
  .chnMux     = kAdcChnMuxOfA
};
      

/* END ADC0. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.11]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
