/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : gpio.h
**     Project     : CB_Test
**     Processor   : MK22FN512VLH12
**     Component   : fsl_gpio
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-03-05, 13:19, # CodeGen: 38
**     Contents    :
**         GPIO_DRV_Init                - void GPIO_DRV_Init(const gpio_input_pin_user_config_t * inputPins,const...
**         GPIO_DRV_InputPinInit        - void GPIO_DRV_InputPinInit(const gpio_input_pin_user_config_t * inputPin);
**         GPIO_DRV_OutputPinInit       - void GPIO_DRV_OutputPinInit(const gpio_output_pin_user_config_t * outputPin);
**         GPIO_DRV_GetPinDir           - gpio_pin_direction_t GPIO_DRV_GetPinDir(uint32_t pinName);
**         GPIO_DRV_SetPinDir           - void GPIO_DRV_SetPinDir(uint32_t pinName,gpio_pin_direction_t direction);
**         GPIO_DRV_WritePinOutput      - void GPIO_DRV_WritePinOutput(uint32_t pinName,uint32_t output);
**         GPIO_DRV_SetPinOutput        - void GPIO_DRV_SetPinOutput(uint32_t pinName);
**         GPIO_DRV_ClearPinOutput      - void GPIO_DRV_ClearPinOutput(uint32_t pinName);
**         GPIO_DRV_TogglePinOutput     - void GPIO_DRV_TogglePinOutput(uint32_t pinName);
**         GPIO_DRV_ReadPinInput        - uint32_t GPIO_DRV_ReadPinInput(uint32_t pinName);
**         GPIO_DRV_SetDigitalFilterCmd - void GPIO_DRV_SetDigitalFilterCmd(uint32_t pinName,bool isDigitalFilterEnabled);
**         GPIO_DRV_ClearPinIntFlag     - void GPIO_DRV_ClearPinIntFlag(uint32_t pinName);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file gpio.h
** @version 01.00
*/         
/*!
**  @addtogroup gpio_module gpio module documentation
**  @{
*/         

#ifndef __gpio_H
#define __gpio_H

/* MODULE gpio. */

/* Include inherited beans */
#include "fsl_gpio_driver.h"



/*! @brief Configuration structure 0 for output pins */
extern const gpio_output_pin_user_config_t gpio_OutConfig0[];

/*! @brief Pin names */
enum _gpio_pinNames{
  ILI9163_RESET = GPIO_MAKE_PIN(HW_GPIOC, 5U),
  ILI9163_A0 = GPIO_MAKE_PIN(HW_GPIOC, 6U),
  ILI9163_SDA = GPIO_MAKE_PIN(HW_GPIOC, 10U),
  ILI9163_SCK = GPIO_MAKE_PIN(HW_GPIOC, 3U),
  ILI9163_CS = GPIO_MAKE_PIN(HW_GPIOC, 7U),
  LED_RED = GPIO_MAKE_PIN(HW_GPIOA, 1U),
  LED_GREEN = GPIO_MAKE_PIN(HW_GPIOA, 2U),
};

  
#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.11]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
