/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Timer1.h
**     Project     : CB_Test
**     Processor   : MK22FN512VLH12
**     Component   : fsl_ftm
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-03-03, 14:46, # CodeGen: 32
**     Contents    :
**         FTM_DRV_Init                  - void FTM_DRV_Init(uint8_t instance,ftm_user_config_t * info);
**         FTM_DRV_Deinit                - void FTM_DRV_Deinit(uint8_t instance);
**         FTM_DRV_PwmStop               - void FTM_DRV_PwmStop(uint8_t instance,ftm_pwm_param_t * param,uint8_t channel);
**         FTM_DRV_PwmStart              - void FTM_DRV_PwmStart(uint8_t instance,ftm_pwm_param_t * param,uint8_t channel);
**         FTM_DRV_QuadDecodeStart       - void FTM_DRV_QuadDecodeStart(uint8_t instance,ftm_phase_params_t *...
**         FTM_DRV_QuadDecodeStop        - void FTM_DRV_QuadDecodeStop(uint8_t instance);
**         FTM_DRV_CounterStart          - void FTM_DRV_CounterStart(uint8_t instance,ftm_counting_mode_t...
**         FTM_DRV_CounterStop           - void FTM_DRV_CounterStop(uint8_t instance);
**         FTM_DRV_CounterRead           - uint32_t FTM_DRV_CounterRead(uint8_t instance);
**         FTM_DRV_SetTimeOverflowIntCmd - void FTM_DRV_SetTimeOverflowIntCmd(uint32_t instance,bool overflowEnable);
**         FTM_DRV_SetFaultIntCmd        - void FTM_DRV_SetFaultIntCmd(uint32_t instance,bool faultEnable);
**         FTM_DRV_IRQHandler            - void FTM_DRV_IRQHandler(uint8_t instance);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Timer1.h
** @version 01.00
*/         
/*!
**  @addtogroup Timer1_module Timer1 module documentation
**  @{
*/         

#ifndef __Timer1_H
#define __Timer1_H

/* MODULE Timer1. */

/* Include inherited beans */

#include "Cpu.h"
#include "fsl_ftm_driver.h"

/*! @brief Device instance number */
#define FSL_TIMER1 0



/*! @brief Configuration 0 */
extern ftm_user_config_t Timer1_InitConfig0;
/* END Timer1. */

#endif 
/* ifndef __Timer1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.11]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
